# Usage:
# docker-compose up
version: '2.4'

services:

  nginx:
    image: "grocy/nginx:v3.0.1-12"
    build:
      args:
        GROCY_VERSION: v3.0.1
      context: .
      dockerfile: Dockerfile-grocy-nginx
    depends_on:
      - grocy
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - /var/log/nginx
    container_name: nginx-grocy
    environment:
      VIRTUAL_HOST: ${GROCY_DOMAIN}
      LETSENCRYPT_HOST: ${GROCY_DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      VIRTUAL_PORT: 8080
  grocy:
    image: "grocy/grocy:v3.0.1-12"
    build:
      args:
        GROCY_VERSION: v3.0.1
      context: .
      dockerfile: Dockerfile-grocy
    expose:
      - '9000'
    read_only: false
    tmpfs:
      - /tmp
    volumes:
      - /var/log/php7
      - app-db:/var/www/data
    env_file:
      - grocy.env
    container_name: grocy

  barcodebuddy:
    image: "f0rc3/barcodebuddy-docker:latest"
    expose:
      - '8081'
    volumes:
      - bbconfig:/config
    container_name: bbuddy
    environment:
      VIRTUAL_HOST: ${BBUDDY_DOMAIN}
      LETSENCRYPT_HOST: ${BBUDDY_DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      VIRTUAL_PORT: 80

volumes:
  app-db:
  bbconfig:

networks:
  default:
    external:
      name: ${NETWORK}