

variable "aws_region" {
  default = "us-east-1"
}

variable "grocy_duckdns_domain" {
  description = "Registered grocy server domain name with https://www.duckdns.org. Visit https://www.duckdns.org and register for a free domain name. This domain name is also used for SSL certificates with LetsEncrypt. This is required."

}

variable "grocy_bbuddy_duckdns_domain" {
  description = "Registered Barcode Buddy server domain name with https://www.duckdns.org. Visit https://www.duckdns.org and register for a free domain name. This domain name is also used for SSL certificates with LetsEncrypt. This is required."

}


variable "duckdns_token" {
  description = "Token generated by DuckDNS that looks something like a7c4d0ad-114e-40ef-ba1d-d217904a50f2. Copy and paste this from DuckDNS once you have registered your domain."

}


variable "ami_key_pair_name" {
  default = "grocy-ssh-keypair"
  description = "SSH key pair name for the EC2 instance"
}


